version: '3.5'

services:
    frontend:
        image: fe-example
        environment: 
            - REACT_APP_BACKEND_URL=http://localhost:8080
        ports: 
            - 5000:5000
        command: ["serve" ,"-s", "-l", "5000" , "build"]

    backend: 
        image: be-example
        environment: 
            - REQUEST_ORIGIN=http://localhost
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DATABASE=example
        ports: 
            - 8080:8080
        command: ["./server"]

    redis:
        image: redis

    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_DB: example
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

    proxy:
        image: nginx
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
        depends_on: 
            - db
            - redis
            - frontend
            - backend

    
    